name : Interacting With Construction Robots
title: Interacting With Construction Robots
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Uncertainty can be an opportunity when humans and robots work together..<br>
  ..But we need good intrefaces!
email: eleni.skevaki@epfl.ch
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
remote_theme: thiagorossener/jekflix-template@v3.1.2
plugins:
  - jekyll-feed
  - jekyll-remote-theme

repository: CRCL-EPFL/sample-site

menu:
  - title: Home
    url: /
  - title: Getting Started
    url: /2025-05-26-getting-started-with-interactions/
  - title: Demos
    url: /2025-05-27-interface-demo/
  - title: Publications
    url: /2025-05-27-interface-demo/
  - title: Conclusion
    url: /2025-05-28-conclusion-and-next-steps/