name : Interacting With Construction Robots
title: Interacting With Construction Robots
email: eleni.skevaki@epfl.ch
description: >- # this means to ignore newlines until "baseurl:"
  Uncertainty can be an opportunity when humans and robots work together..
  ..But we need good intrefaces!
show_hero: false
email: eleni.skevaki@epfl.ch
sent_message_url: "/contact/message-sent/"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://iwcr.crclcrclcrcl.org"
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
remote_theme: thiagorossener/jekflix-template@v3.1.2
plugins:
  - jekyll-feed
  - jekyll-remote-theme

repository: CRCL-EPFL/sample-site

defaults:
  - scope:
      path: ""       # apply everywhere
      type: "pages"  # only files treated as pages
      layout: "home" # only to files using layout: home
    values:
      image: "/assets/img/blog-image.png"

menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Publications
    url: /publications
  - title: Contact
    url: /contact/

# Social Media Settings
# Remove the item if you don't need it
github_username: eleniv3d
instagram_username: elenived
linkedin_username: eleni-skevaki-3b21ba59