name : Interacting With Construction Robots
title: Interacting With Construction Robots
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Uncertainty can be an opportunity when humans and robots work together..<br>
  ..But we need good intrefaces!
email: eleni.skevaki@epfl.ch
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://iwcr.crclcrclcrcl.org"
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
remote_theme: thiagorossener/jekflix-template@v3.1.2
plugins:
  - jekyll-feed
  - jekyll-remote-theme

repository: CRCL-EPFL/sample-site

menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Publications
    url: /publications
  - title: Contact
    url: /contact/